[techmeme]
title = "Techmeme"
url = "https://www.techmeme.com/"
entrySelector = "ii"
titleSelector = "strong"
linkSelector = "strong a"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
